/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hibernate.demo;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.service.ServiceRegistry;
import org.hibernate.service.ServiceRegistryBuilder;


public class App {

    public static void main(String[] args) {
        
        Configuration con = new Configuration().configure().addAnnotatedClass(Laptop.class);

        ServiceRegistry reg = new ServiceRegistryBuilder().applySettings(con.getProperties()).buildServiceRegistry();
        
        SessionFactory sf = con.buildSessionFactory(reg);    
        
        Session session = sf.openSession();
        
        Transaction tx = session.beginTransaction();
        
        Laptop l1 = (Laptop)session.get(Laptop.class, 101);
        
        System.out.println(l1);
      
        
        tx.commit();
        
        
       
    }
}
